export const REDS_URL = "https://nourewellness.com/products/reds-superfood";

export type Phase = { week: 1 | 2 | 3; label: string; range: [number, number] };
export const PHASES: Phase[] = [
  { week: 1, label: "Foundation", range: [1, 7] },
  { week: 2, label: "Build", range: [8, 14] },
  { week: 3, label: "Glow", range: [15, 21] },
];

export function phaseFor(day: number): Phase {
  return PHASES.find((p) => day >= p.range[0] && day <= p.range[1])!;
}

export type Day = { day: number; title: string; teaser: string; guide: string; recipeId: string };

export const DAYS: Day[] = [
  { day: 1, title: "The First Glass", recipeId: "pomegranate-elixir",
    teaser: "Today the ritual begins. One glass. One quiet morning.",
    guide: "Today is about beginning. Not perfectly — just beginning. Pour your warm water with lemon, then prepare your Radiant Reds. Drink slowly. Notice the color. The polyphenols you're taking in this morning — ellagic acid, anthocyanins, punicalagins — are already moving toward your gut lining, where the gut-skin axis begins. You won't see the result today. That's not the point. Today's only job: show up." },
  { day: 2, title: "Stillness Before Speed", recipeId: "berry-bloom",
    teaser: "Five quiet minutes before the day asks anything of you.",
    guide: "Before you check your phone, sit for five minutes with your glass. This isn't meditation — it's permission. Your nervous system sets the tone for digestion. A calm morning means a calm gut. A calm gut means clearer skin. Today, drink slow. Breathe slower." },
  { day: 3, title: "The Polyphenol Window", recipeId: "cherry-cacao",
    teaser: "Your morning is when polyphenols absorb best.",
    guide: "Polyphenols absorb best on a relatively empty stomach with hydration. That's why this ritual lives in the morning. Today, layer in tart cherry — one of the highest-anthocyanin foods studied for skin elasticity and recovery." },
  { day: 4, title: "Listening Inward", recipeId: "plum-rose",
    teaser: "Your body has been answering. Today you listen.",
    guide: "Four mornings in, your body has begun to respond. Bloating may have softened. Energy may feel a touch steadier. Skin won't show change yet — that's still days away. Today's ritual: drink, then write one sentence about what your body is saying." },
  { day: 5, title: "The Skin-Gut Bridge", recipeId: "watermelon-reds",
    teaser: "What you feed your gut, your skin wears.",
    guide: "The gut-skin axis isn't a metaphor. Inflammation in the gut lining shows up as dullness, breakouts, sensitivity. Polyphenols feed the bacteria that protect that lining. Today's recipe is hydration-forward — watermelon and hibiscus to flush and feed at once." },
  { day: 6, title: "The Quiet Build", recipeId: "fig-almond",
    teaser: "Day 6. Nothing dramatic. Everything compounding.",
    guide: "Six mornings of polyphenols, fiber, and stillness. Your microbiome has noticed. Your skin hasn't shown the world yet, but it's listening. Today, add fig — a quiet, fiber-rich addition that supports the gut bacteria you've been feeding all week." },
  { day: 7, title: "One Full Week", recipeId: "beet-glow",
    teaser: "One week. Foundation complete.",
    guide: "You've built the foundation. Seven mornings of ritual is no longer a beginning — it's a pattern. Today's recipe brings beet, one of the most studied roots for circulation and skin oxygenation. Drink it. Then look in the mirror. Notice without judgement. Week two starts tomorrow." },
  { day: 8, title: "Build Begins", recipeId: "pomegranate-elixir",
    teaser: "Week 2. Now we deepen.",
    guide: "Foundation is built. Now we layer. This week the ritual starts to feel less like a task and more like a morning. Today, return to the pomegranate elixir — but this time, taste it differently. The same glass becomes the same ritual every morning, but you are not the same person who drank it on day one." },
  { day: 9, title: "The Ferment Layer", recipeId: "berry-bloom",
    teaser: "Add a small fermented food today.",
    guide: "Today, alongside your reds, eat a small fermented food — yogurt, kefir, kimchi, sauerkraut. Polyphenols and probiotics work together: the polyphenols feed the bacteria, the bacteria metabolize the polyphenols into the compounds your skin actually uses." },
  { day: 10, title: "Day 10 — Ten Mornings", recipeId: "cherry-cacao",
    teaser: "Ten mornings in. The ritual is becoming yours.",
    guide: "Ten mornings is no longer 'trying it.' Ten mornings is a practice. Today, drink your reds, then notice: what feels different from day one? Not in the mirror — inside." },
  { day: 11, title: "Watching for the Shift", recipeId: "plum-rose",
    teaser: "Dullness lifts in week two. Watch for it.",
    guide: "Around day 11–14, many notice the first visible shift: a softening of dullness, a small lift in tone. It's subtle. It's compounding. Today's ritual: drink, then take a quiet photo of your skin in natural light. You'll want it later." },
  { day: 12, title: "The Skin Speaks", recipeId: "watermelon-reds",
    teaser: "Your skin has been working. Today it shows you.",
    guide: "Your skin renews on a roughly 27-day cycle, but the brightness of the surface — that comes faster. Twelve days of feeding your gut-skin axis means a freshly turned-over surface layer. Today, hydrate hard. Watermelon, hibiscus, lime." },
  { day: 13, title: "Almost Halfway Through Build", recipeId: "fig-almond",
    teaser: "Tomorrow is the halfway mark.",
    guide: "Tomorrow is day 14 — the halfway point. Today, take inventory. What three things feel different? Write them in your journal. Then drink your reds slowly. The ritual rewards attention." },
  { day: 14, title: "Halfway", recipeId: "beet-glow",
    teaser: "Halfway. The ritual is yours now.",
    guide: "Fourteen mornings. The ritual is no longer something you're doing — it's something you have. Week three is where the work becomes visible. Today, beet again, for circulation. Then sit with the feeling of having shown up fourteen times in a row." },
  { day: 15, title: "Week 3 — Glow Begins", recipeId: "pomegranate-elixir",
    teaser: "This is the week your skin shows the work.",
    guide: "Week three is where the inside surfaces. Your microbiome is noticeably more diverse. Your skin's surface layer is fresher. The polyphenols you've been drinking are now circulating in measurable amounts. Today, return to pomegranate. The first recipe. Notice how different it tastes when you've been drinking it for fifteen mornings." },
  { day: 16, title: "What the Mirror Shows", recipeId: "berry-bloom",
    teaser: "What your mirror shows now is what you built.",
    guide: "Today, look at the photo you took on day 11. Look at your skin now. Don't expect drama. Look for: clarity, tone, that small lift in the under-eye. It's the kind of glow that other people notice first." },
  { day: 17, title: "Four Days Left", recipeId: "cherry-cacao",
    teaser: "Don't stop here.",
    guide: "Four mornings remain. This is the stretch where many quit because they think they've gotten what they came for. Don't. Days 17–21 are where the ritual locks in for the long term. Today: tart cherry, full ritual, full attention." },
  { day: 18, title: "Compounding", recipeId: "plum-rose",
    teaser: "The glow you're seeing is compounding.",
    guide: "Each polyphenol you've taken in has built on the one before. The benefit isn't from one glass — it's from eighteen. This is why 21 days. This is why ritual. Today, plum and rose, and a slow morning." },
  { day: 19, title: "Two Mornings After This", recipeId: "watermelon-reds",
    teaser: "Two more mornings after today.",
    guide: "Three mornings left including today. This week, start to think about what happens on day 22. The ritual that has worked for 21 days is the ritual that works for 121 days. Don't change it just because the count ends." },
  { day: 20, title: "Day 20 — Almost", recipeId: "fig-almond",
    teaser: "Tomorrow is Day 21. You made it.",
    guide: "Tomorrow is the final morning. Today, drink your reds, eat your fig, and write a long journal entry. Tomorrow's entry will be a letter — today's is the setup." },
  { day: 21, title: "Day 21 — The Ritual Holds", recipeId: "beet-glow",
    teaser: "This is Day 21. You showed up.",
    guide: "Twenty-one mornings. You showed up for a ritual most people won't. Drink the final glass slowly. Then open your celebration screen. The ritual doesn't end here — it just stops being a 21-day reset and starts being your morning." },
];

export type Recipe = {
  id: string; name: string; gradient: string; prep: string; servings: string;
  benefit: string; benefitTag: string; ingredients: string[]; method: string[];
  redsBoost: { why: string; proof: string[] };
  bonus?: boolean;
  /** Quick Glow Mornings — bonus five-minute smoothies outside the 21-day rotation */
  quick?: boolean;
  /** Optional override path for smoothie photo. Defaults to /images/smoothies/${id}.jpg */
  image?: string;
};

// Elegant, feminine, light gradients — NO red. Plum, gold, sand, sage, lavender, dusty rose, cream.
const G = {
  plumGold:    "linear-gradient(135deg, #7B2D4E 0%, #C49A6C 100%)",
  goldSand:    "linear-gradient(135deg, #C49A6C 0%, #F1EAE2 100%)",
  plumLavender:"linear-gradient(135deg, #7B2D4E 0%, #B8A9C9 100%)",
  sageIvory:   "linear-gradient(135deg, #A8B5A0 0%, #FAF7F4 100%)",
  roseSand:    "linear-gradient(135deg, #D9B8B0 0%, #F1EAE2 100%)",
  creamGold:   "linear-gradient(135deg, #F4E9D8 0%, #C49A6C 100%)",
  plumSage:    "linear-gradient(135deg, #7B2D4E 0%, #A8B5A0 100%)",
  goldRose:    "linear-gradient(135deg, #C49A6C 0%, #D9B8B0 100%)",
  plumDeep:    "linear-gradient(135deg, #5C2541 0%, #7B2D4E 100%)",
  lavenderIvory:"linear-gradient(135deg, #B8A9C9 0%, #FAF7F4 100%)",
  sandPlum:    "linear-gradient(135deg, #F1EAE2 0%, #7B2D4E 100%)",
  goldLavender:"linear-gradient(135deg, #C49A6C 0%, #B8A9C9 100%)",
  sageGold:    "linear-gradient(135deg, #A8B5A0 0%, #C49A6C 100%)",
  roseGold:    "linear-gradient(135deg, #D9B8B0 0%, #C49A6C 100%)",
};

const REDS_PROOF = {
  skin:    ["Pomegranate punicalagins protect collagen", "Hibiscus anthocyanins support even tone", "Açaí flavonoids defend against oxidative stress", "Beet nitrates oxygenate the skin"],
  glow:    ["27 polyphenol sources in one scoop", "Feeds the gut bacteria your skin depends on", "Compounds with daily ritual use", "Visible lift around Day 14"],
  energy:  ["Beet nitrates increase cellular oxygen", "Polyphenols stabilize morning energy", "No caffeine spike, no crash", "Pairs with whole-food breakfast"],
  gut:     ["Polyphenols feed bifidobacteria diversity", "Soluble fibers support a calm gut lining", "Prebiotic action begins within 72 hours", "Supports the gut–skin axis directly"],
  hydration:["Mineral-rich hibiscus and beet", "Supports vascular hydration", "Pairs perfectly with morning water", "Replenishes after sleep"],
  recovery:["Anti-inflammatory polyphenol matrix", "Tart cherry-style melatonin support", "Calms morning puffiness", "Restores after late nights"],
};

export const RECIPES: Recipe[] = [
  // ——— 21 CORE RECIPES ———
  { id: "pomegranate-elixir", name: "The Pomegranate Glow Elixir", gradient: G.plumGold,
    prep: "4 min", servings: "1", benefitTag: "Skin clarity",
    benefit: "Supports the gut–skin axis with ellagic acid and punicalagins from pomegranate. Skin clarity benefit begins around Day 5.",
    ingredients: ["Pomegranate", "Raspberry", "Oat milk", "Radiant Reds", "Lime"],
    method: ["Add 1 cup pomegranate seeds and ½ cup raspberries to a blender.", "Pour in 1 cup oat milk and one scoop Radiant Reds.", "Squeeze in half a lime. Blend until silky.", "Pour into a chilled glass. Drink slowly."],
    redsBoost: { why: "Radiant Reds layers a second wave of pomegranate and beet polyphenols on top of the fresh fruit — doubling the skin-clarity load in a single glass.", proof: REDS_PROOF.skin } },
  { id: "berry-bloom", name: "Berry Bloom", gradient: G.plumLavender,
    prep: "3 min", servings: "1", benefitTag: "Antioxidant",
    benefit: "Anthocyanin-rich blueberries and strawberries to feed your microbiome and brighten dull mornings.",
    ingredients: ["Blueberry", "Strawberry", "Banana", "Almond milk", "Chia"],
    method: ["Combine 1 cup mixed berries with half a banana.", "Add 1 cup almond milk and 1 tbsp chia.", "Blend 30 seconds. Let sit 2 minutes for chia to bloom.", "Stir and serve."],
    redsBoost: { why: "Add a scoop of Radiant Reds to fold in 27 additional polyphenol sources your berries can't reach alone.", proof: REDS_PROOF.glow } },
  { id: "cherry-cacao", name: "Cherry Cacao", gradient: G.plumDeep,
    prep: "4 min", servings: "1", benefitTag: "Recovery",
    benefit: "Tart cherry brings melatonin and anthocyanins for skin recovery; cacao adds flavanols for circulation.",
    ingredients: ["Tart cherry", "Cacao", "Almond butter", "Oat milk", "Cinnamon"],
    method: ["Blend 1 cup tart cherries with 1 tbsp cacao.", "Add 1 tbsp almond butter and 1 cup oat milk.", "Pinch of cinnamon. Blend until smooth."],
    redsBoost: { why: "Radiant Reds amplifies the recovery profile with hibiscus and açaí — calming inflammation while you sleep it off.", proof: REDS_PROOF.recovery } },
  { id: "plum-rose", name: "Plum & Rose", gradient: G.roseSand,
    prep: "5 min", servings: "1", benefitTag: "Soothing",
    benefit: "Plum polyphenols paired with rose water for a calming, anti-inflammatory ritual.",
    ingredients: ["Plum", "Rose water", "Coconut yogurt", "Honey"],
    method: ["Pit and slice 2 ripe plums.", "Blend with ½ cup coconut yogurt and 1 tsp rose water.", "Sweeten with a touch of honey."],
    redsBoost: { why: "A small scoop of Radiant Reds turns this gentle bowl into a full polyphenol ritual without changing its softness.", proof: REDS_PROOF.skin } },
  { id: "watermelon-reds", name: "Watermelon Hibiscus", gradient: G.goldRose,
    prep: "3 min", servings: "1", benefitTag: "Hydration",
    benefit: "Hydration-forward with hibiscus for vascular support and Radiant Reds for the polyphenol layer.",
    ingredients: ["Watermelon", "Hibiscus tea", "Lime", "Radiant Reds"],
    method: ["Brew 1 cup hibiscus tea, cool fully.", "Blend with 2 cups watermelon, lime juice.", "Stir in one scoop Radiant Reds."],
    redsBoost: { why: "Radiant Reds is what makes this glass more than juice — adding the polyphenol density watermelon alone can't deliver.", proof: REDS_PROOF.hydration } },
  { id: "fig-almond", name: "Fig & Almond", gradient: G.creamGold,
    prep: "5 min", servings: "1", benefitTag: "Gut",
    benefit: "Black fig for fiber and prebiotics, almond for healthy fats your skin barrier needs.",
    ingredients: ["Black fig", "Almond", "Oat milk", "Cinnamon"],
    method: ["Blend 3 black figs with a small handful of almonds.", "Add 1 cup oat milk and a pinch of cinnamon.", "Blend until creamy."],
    redsBoost: { why: "Radiant Reds layers prebiotic polyphenols on top of fig fiber — the duo your microbiome responds to fastest.", proof: REDS_PROOF.gut } },
  { id: "beet-glow", name: "Beet Glow", gradient: G.plumGold,
    prep: "6 min", servings: "1", benefitTag: "Circulation",
    benefit: "Beet for nitric oxide and skin oxygenation, raspberry for ellagitannins, ginger for warmth.",
    ingredients: ["Beet", "Raspberry", "Ginger", "Orange"],
    method: ["Roast or steam 1 small beet ahead of time.", "Blend with ½ cup raspberries, a thumb of ginger, and the juice of 1 orange.", "Strain if you want it silky."],
    redsBoost: { why: "Radiant Reds doubles the beet nitrate load, deepening circulation and the lit-from-within glow this recipe is built for.", proof: REDS_PROOF.energy } },
  { id: "golden-turmeric", name: "Golden Turmeric Latte", gradient: G.creamGold,
    prep: "5 min", servings: "1", benefitTag: "Calm",
    benefit: "Curcumin with healthy fat and black pepper — the classic anti-inflammatory morning warmth.",
    ingredients: ["Turmeric", "Oat milk", "Cinnamon", "Honey", "Almond"],
    method: ["Warm 1 cup oat milk gently.", "Whisk in ½ tsp turmeric, pinch of cinnamon, pinch of black pepper.", "Sweeten with honey. Top with crushed almond."],
    redsBoost: { why: "A scoop of Radiant Reds stirred into the cooled latte adds polyphenols turmeric can't deliver alone.", proof: REDS_PROOF.gut } },
  { id: "matcha-cloud", name: "Matcha Cloud", gradient: G.sageIvory,
    prep: "4 min", servings: "1", benefitTag: "EGCG",
    benefit: "Ceremonial matcha for EGCG — one of the most-studied polyphenols for skin protection.",
    ingredients: ["Green tea", "Almond milk", "Honey", "Banana"],
    method: ["Whisk 1 tsp matcha with 2 tbsp warm water until smooth.", "Blend with ½ banana, ¾ cup almond milk, drizzle of honey.", "Pour over ice."],
    redsBoost: { why: "Radiant Reds pairs EGCG with anthocyanins — two polyphenol families your skin uses through different pathways.", proof: REDS_PROOF.skin } },
  { id: "lavender-honey", name: "Lavender Honey Tonic", gradient: G.lavenderIvory,
    prep: "3 min", servings: "1", benefitTag: "Calm",
    benefit: "Culinary lavender steeped with raw honey — soft on the nervous system, kind to digestion.",
    ingredients: ["Rose water", "Honey", "Lemon", "Mint"],
    method: ["Steep 1 tsp culinary lavender in 1 cup hot water for 4 minutes.", "Strain. Stir in honey and a squeeze of lemon.", "Garnish with mint."],
    redsBoost: { why: "After it cools, stir in a scoop of Radiant Reds — calm becomes a full polyphenol ritual.", proof: REDS_PROOF.recovery } },
  { id: "rose-cardamom", name: "Rose Cardamom Mylk", gradient: G.roseSand,
    prep: "5 min", servings: "1", benefitTag: "Soothing",
    benefit: "Cardamom and rose with creamy oat milk — feminine, warming, anti-inflammatory.",
    ingredients: ["Oat milk", "Rose water", "Cinnamon", "Honey"],
    method: ["Warm 1 cup oat milk with a pinch of crushed cardamom and cinnamon.", "Off heat, stir in 1 tsp rose water and honey.", "Sip slowly."],
    redsBoost: { why: "Radiant Reds folds in beautifully once the mylk cools to drinking temperature, adding the polyphenol layer.", proof: REDS_PROOF.skin } },
  { id: "blueberry-basil", name: "Blueberry Basil", gradient: G.plumLavender,
    prep: "4 min", servings: "1", benefitTag: "Antioxidant",
    benefit: "Wild blueberries with fresh basil — anthocyanins meet aromatic polyphenols.",
    ingredients: ["Blueberry", "Banana", "Almond milk", "Mint", "Lemon"],
    method: ["Blend 1 cup wild blueberries, ½ banana, 4 basil leaves.", "Add 1 cup almond milk and lemon zest.", "Blend until smooth."],
    redsBoost: { why: "A scoop of Radiant Reds compounds the anthocyanin load — your microbiome converts both into the metabolites your skin uses.", proof: REDS_PROOF.glow } },
  { id: "papaya-lime", name: "Papaya Lime", gradient: G.goldRose,
    prep: "3 min", servings: "1", benefitTag: "Digestive",
    benefit: "Papaya enzymes plus citrus for a glowing, easy-digesting morning.",
    ingredients: ["Watermelon", "Lime", "Mint", "Coconut yogurt"],
    method: ["Blend 1½ cups papaya with the juice of 1 lime.", "Stir in 2 tbsp coconut yogurt and torn mint.", "Serve cold."],
    redsBoost: { why: "Radiant Reds adds the polyphenol density papaya is missing — turning a digestive glass into a full-spectrum ritual.", proof: REDS_PROOF.gut } },
  { id: "peach-saffron", name: "Peach & Saffron", gradient: G.creamGold,
    prep: "5 min", servings: "1", benefitTag: "Mood",
    benefit: "A pinch of saffron with stone fruit — traditionally used for steady mood and skin tone.",
    ingredients: ["Plum", "Honey", "Almond milk", "Cinnamon"],
    method: ["Steep a small pinch of saffron in 2 tbsp warm almond milk.", "Blend with 1 ripe peach, ½ cup almond milk, honey.", "Top with cinnamon."],
    redsBoost: { why: "Radiant Reds layers anthocyanins and ellagitannins — supporting the steady tone saffron is famous for.", proof: REDS_PROOF.skin } },
  { id: "fig-vanilla", name: "Fig & Vanilla Cream", gradient: G.creamGold,
    prep: "4 min", servings: "1", benefitTag: "Gut",
    benefit: "Black mission figs blended with vanilla and oat milk — silky, prebiotic, skin-kind.",
    ingredients: ["Black fig", "Oat milk", "Honey", "Cinnamon", "Almond"],
    method: ["Blend 4 figs with 1 cup oat milk.", "Add ¼ tsp vanilla and a drizzle of honey.", "Top with crushed almond."],
    redsBoost: { why: "Radiant Reds amplifies the prebiotic effect of fig fiber — a 1+1=3 combination for the microbiome.", proof: REDS_PROOF.gut } },
  { id: "cucumber-mint", name: "Cucumber Mint Cooler", gradient: G.sageIvory,
    prep: "3 min", servings: "1", benefitTag: "Hydration",
    benefit: "Pure hydration with mineral-rich cucumber and cooling mint.",
    ingredients: ["Watermelon", "Lime", "Mint", "Hibiscus tea"],
    method: ["Blend 1 cucumber with the juice of ½ lime and a small handful of mint.", "Strain over ice.", "Top with sparkling water."],
    redsBoost: { why: "Stir in a scoop of Radiant Reds — the only thing this glass is missing is polyphenols.", proof: REDS_PROOF.hydration } },
  { id: "apricot-almond", name: "Apricot Almond Glow", gradient: G.goldSand,
    prep: "4 min", servings: "1", benefitTag: "Skin",
    benefit: "Apricots are quietly carotenoid-rich — a soft, lit-from-within tone enhancer.",
    ingredients: ["Plum", "Almond", "Oat milk", "Honey"],
    method: ["Blend 3 ripe apricots with a small handful of almonds.", "Add ¾ cup oat milk and honey.", "Blend until silky."],
    redsBoost: { why: "Radiant Reds pairs carotenoids with anthocyanins — the two pigment families your glow is built on.", proof: REDS_PROOF.skin } },
  { id: "kiwi-spinach", name: "Kiwi Spinach Light", gradient: G.sageGold,
    prep: "4 min", servings: "1", benefitTag: "Vitamin C",
    benefit: "Kiwi for vitamin C, baby spinach for chlorophyll — a quietly powerful skin-tone glass.",
    ingredients: ["Lime", "Banana", "Almond milk", "Mint"],
    method: ["Blend 2 kiwis with a handful of baby spinach.", "Add ½ banana, 1 cup almond milk.", "Squeeze in lime."],
    redsBoost: { why: "Radiant Reds completes the picture — chlorophyll plus polyphenols cover the full plant-pigment spectrum.", proof: REDS_PROOF.glow } },
  { id: "vanilla-chia", name: "Vanilla Chia Pudding", gradient: G.creamGold,
    prep: "5 min + chill", servings: "1", benefitTag: "Omega-3",
    benefit: "Plant omega-3, slow-release fiber, soft vanilla cream — the gentle skin-barrier breakfast.",
    ingredients: ["Chia", "Oat milk", "Honey", "Cinnamon", "Almond"],
    method: ["Stir 3 tbsp chia into 1 cup oat milk with vanilla and honey.", "Refrigerate overnight.", "Top with crushed almond and cinnamon."],
    redsBoost: { why: "Sprinkle a scoop of Radiant Reds on top — omega-3 + polyphenols is the barrier-and-glow combo your skin asks for.", proof: REDS_PROOF.skin } },
  { id: "ginger-pear", name: "Ginger Pear Warmth", gradient: G.goldSand,
    prep: "4 min", servings: "1", benefitTag: "Digestive",
    benefit: "Pear and warming ginger — gentle morning motility with quiet polyphenol density.",
    ingredients: ["Ginger", "Orange", "Honey", "Cinnamon"],
    method: ["Blend 1 ripe pear with a thumb of ginger and the juice of ½ orange.", "Sweeten with honey, dust with cinnamon.", "Serve over ice or warm."],
    redsBoost: { why: "Radiant Reds turns digestive comfort into a polyphenol ritual — the same glass, twice the work.", proof: REDS_PROOF.gut } },
  { id: "honey-almond", name: "Honey Almond Tonic", gradient: G.creamGold,
    prep: "3 min", servings: "1", benefitTag: "Energy",
    benefit: "Raw honey, almond, oat milk — clean morning energy without caffeine.",
    ingredients: ["Almond", "Oat milk", "Honey", "Cinnamon"],
    method: ["Blend 1 tbsp almond butter with 1 cup oat milk.", "Add 1 tsp raw honey and a dash of cinnamon.", "Serve warm or cold."],
    redsBoost: { why: "Stir in Radiant Reds for steady, polyphenol-backed energy that doesn't crash.", proof: REDS_PROOF.energy } },

  // ——— 5 BONUS RECIPES (live in Bonuses tab) ———
  { id: "bonus-cacao-tonic", name: "Midnight Cacao Tonic", gradient: G.plumDeep, bonus: true,
    prep: "5 min", servings: "1", benefitTag: "Bonus · Wind-down",
    benefit: "An evening polyphenol ritual — cacao flavanols and warm spice for skin recovery while you sleep.",
    ingredients: ["Cacao", "Oat milk", "Cinnamon", "Honey"],
    method: ["Warm 1 cup oat milk gently.", "Whisk in 1 tbsp cacao, pinch of cinnamon, drizzle of honey.", "Sip an hour before bed."],
    redsBoost: { why: "A small scoop of Radiant Reds in the evening adds the recovery polyphenols your skin uses overnight.", proof: REDS_PROOF.recovery } },
  { id: "bonus-rose-collagen", name: "Rose Collagen Float", gradient: G.roseSand, bonus: true,
    prep: "3 min", servings: "1", benefitTag: "Bonus · Skin",
    benefit: "A delicate collagen-supportive sip — vitamin C, rose, and gold-flecked elegance.",
    ingredients: ["Rose water", "Lime", "Honey", "Strawberry"],
    method: ["Muddle 4 strawberries with lime juice.", "Top with sparkling water and 1 tsp rose water.", "Drizzle honey, stir gently."],
    redsBoost: { why: "Radiant Reds completes the collagen support story — vitamin C + polyphenols is the proven duo.", proof: REDS_PROOF.skin } },
  { id: "bonus-green-glow", name: "The Green Glow", gradient: G.sageGold, bonus: true,
    prep: "4 min", servings: "1", benefitTag: "Bonus · Detox",
    benefit: "Cucumber, mint, kiwi, lime — a chlorophyll-forward midday reset.",
    ingredients: ["Lime", "Mint", "Banana", "Almond milk"],
    method: ["Blend 1 cucumber, 2 kiwis, handful of mint.", "Add ½ banana and ½ cup almond milk.", "Squeeze in lime."],
    redsBoost: { why: "Radiant Reds rounds out the green pigments with the red-pigment polyphenols your skin also wants.", proof: REDS_PROOF.glow } },
  { id: "bonus-warm-elixir", name: "Warm Berry Elixir", gradient: G.plumGold, bonus: true,
    prep: "6 min", servings: "1", benefitTag: "Bonus · Comfort",
    benefit: "A warm winter-morning polyphenol cup for when cold smoothies feel too sharp.",
    ingredients: ["Blueberry", "Hibiscus tea", "Honey", "Cinnamon", "Ginger"],
    method: ["Steep hibiscus tea with a thumb of ginger for 6 minutes.", "Stir in muddled blueberries, honey, cinnamon.", "Strain and sip."],
    redsBoost: { why: "Once it cools to drinking temperature, stir in Radiant Reds — heat-sensitive polyphenols stay intact.", proof: REDS_PROOF.skin } },
  { id: "bonus-glow-sorbet", name: "Glow Sorbet Bowl", gradient: G.lavenderIvory, bonus: true,
    prep: "5 min", servings: "1", benefitTag: "Bonus · Treat",
    benefit: "A frozen ritual — banana, berry, almond cream — the dessert that loves your skin back.",
    ingredients: ["Blueberry", "Banana", "Almond", "Coconut yogurt", "Honey"],
    method: ["Blend 1 frozen banana with ½ cup frozen blueberries.", "Add 2 tbsp coconut yogurt and 1 tbsp almond butter.", "Scoop into a chilled bowl, drizzle honey."],
    redsBoost: { why: "Sprinkle Radiant Reds on top — sorbet becomes a polyphenol ritual without losing the indulgence.", proof: REDS_PROOF.glow } },

  // ——— QUICK GLOW MORNINGS — 7 bonus five-minute smoothies (outside the 21-day rotation) ———
  { id: "berry-reds-yogurt-shake", name: "Berry Reds Yogurt Shake", gradient: G.plumGold, quick: true,
    prep: "4 min", servings: "1", benefitTag: "Steady",
    benefit: "Creamy, antioxidant-rich, and quietly filling.",
    ingredients: ["1 cup frozen mixed berries", "1/2 cup Greek yogurt or kefir", "3/4 cup almond milk", "1 tsp chia seeds", "1/2 banana (optional)", "1 scoop Radiant Reds (Glow Boost)"],
    method: ["Add almond milk, yogurt, berries, chia, and banana to the blender.", "Blend until smooth, about 30 seconds.", "Add your Glow Boost and pulse twice to keep the color bright.", "Pour and sip slowly.", "Texture — thick and spoonable; add a splash more almond milk to drink it.", "Swap — no kefir? Plain Greek yogurt works. Dairy-free: coconut yogurt + oat milk."],
    redsBoost: { why: "Folded into a berry-and-yogurt base, a scoop of Radiant Reds layers in concentrated polyphenols from red superfruits.", proof: ["Polyphenol-rich pomegranate, açaí, and beetroot", "Supports skin radiance and antioxidant protection"] } },
  { id: "pomegranate-vanilla-glow", name: "Pomegranate Vanilla Glow", gradient: G.creamGold, quick: true,
    prep: "4 min", servings: "1", benefitTag: "Radiant",
    benefit: "Bright, polyphenol-rich, and a little luxurious.",
    ingredients: ["1/2 cup pomegranate juice", "1 cup frozen strawberries", "1/2 cup Greek yogurt", "1/4 tsp vanilla extract", "1/2 cup ice", "1 scoop Radiant Reds (Glow Boost)"],
    method: ["Pour pomegranate juice into the blender first.", "Add strawberries, yogurt, vanilla, and ice.", "Blend until silky.", "Stir in your Glow Boost at the end.", "Texture — light and pourable, almost like a drinkable sorbet.", "Swap — use frozen cherries for a deeper, less sweet flavor."],
    redsBoost: { why: "Pomegranate is already one of the most polyphenol-rich fruits — the Glow Boost concentrates that even further.", proof: ["Concentrated red-fruit polyphenols", "Antioxidant support for everyday radiance"] } },
  { id: "cucumber-mint-lightness", name: "Cucumber Mint Lightness Smoothie", gradient: G.sageIvory, quick: true,
    prep: "5 min", servings: "1", benefitTag: "Refreshed",
    benefit: "Crisp, cooling, and feather-light.",
    ingredients: ["1/2 cucumber, roughly chopped", "1 cup frozen pineapple", "Juice of 1/2 lime", "4–5 fresh mint leaves", "3/4 cup coconut water", "1 tsp chia seeds", "1 scoop Radiant Reds (Glow Boost)"],
    method: ["Add coconut water, cucumber, and pineapple to the blender.", "Add lime, mint, and chia.", "Blend until smooth and pale green.", "Finish with your Glow Boost and a quick pulse.", "Texture — thin and refreshing; best served over ice.", "Swap — no fresh mint? A drop of mint extract works. Honeydew can stand in for cucumber."],
    redsBoost: { why: "A scoop of Radiant Reds adds antioxidant depth to an otherwise light, hydrating blend.", proof: ["Polyphenols from red superfruits", "Antioxidant support without heaviness"] } },
  { id: "cherry-cacao-calm-glow", name: "Cherry Cacao Calm Glow", gradient: G.plumDeep, quick: true,
    prep: "4 min", servings: "1", benefitTag: "Calm",
    benefit: "Rich, chocolatey, and grounding.",
    ingredients: ["1 cup frozen cherries", "1 tbsp cacao powder", "1/2 banana", "1/2 cup Greek yogurt", "3/4 cup almond milk", "1 scoop Radiant Reds (Glow Boost)"],
    method: ["Add almond milk, cherries, banana, and yogurt to the blender.", "Add cacao and blend until smooth.", "Stir in your Glow Boost at the end.", "Texture — velvety and dessert-like; add ice for a thicker, colder finish.", "Swap — frozen blueberries can replace cherries. Oat milk for a creamier dairy-free version."],
    redsBoost: { why: "Cherries and cacao bring their own polyphenols; the Glow Boost rounds out the antioxidant profile.", proof: ["Polyphenol-rich red superfruits", "Supports antioxidant protection"] } },
  { id: "peach-ginger-gut-glow", name: "Peach Ginger Gut-Glow", gradient: G.goldSand, quick: true,
    prep: "5 min", servings: "1", benefitTag: "Balanced",
    benefit: "Warm-spiced, golden, and gentle.",
    ingredients: ["1 cup frozen peaches", "1/2 inch fresh ginger (or 1/4 tsp ground)", "1 tbsp ground flax or chia seeds", "1/2 cup Greek yogurt or kefir", "3/4 cup coconut water", "1 scoop Radiant Reds (Glow Boost)"],
    method: ["Add coconut water, peaches, and ginger to the blender.", "Add flax or chia and yogurt.", "Blend until smooth and golden.", "Finish with your Glow Boost.", "Texture — smooth with a little body from the flax; thin with extra coconut water if needed.", "Swap — frozen mango works in place of peaches. Skip the ginger if you prefer it mellow."],
    redsBoost: { why: "A scoop of Radiant Reds adds concentrated red-fruit polyphenols to this gentle, golden blend.", proof: ["Polyphenols from pomegranate and beetroot", "Antioxidant support from within"] } },
  { id: "mocha-reds-morning", name: "Mocha Reds Morning Smoothie", gradient: G.sandPlum, quick: true,
    prep: "4 min", servings: "1", benefitTag: "Energized",
    benefit: "Coffee and breakfast in one glass.",
    ingredients: ["1/2 cup cold brew or chilled coffee", "1 tbsp cacao powder", "1 scoop vanilla protein or 1/2 cup Greek yogurt", "1 frozen banana", "1/2 cup almond milk", "1 scoop Radiant Reds (Glow Boost)"],
    method: ["Add coffee, almond milk, banana, and protein or yogurt to the blender.", "Add cacao and blend until smooth.", "Stir in your Glow Boost at the end.", "Texture — creamy and frothy; add a few ice cubes if you like it colder.", "Swap — decaf or half-caf works just as well. Oat milk for extra creaminess."],
    redsBoost: { why: "Folded into coffee and cacao, the Glow Boost adds polyphenols alongside your morning caffeine.", proof: ["Concentrated red-superfruit polyphenols", "Antioxidant support to start the day"] } },
  { id: "tropical-reds-quickie", name: "Tropical Reds Quickie", gradient: G.sageGold, quick: true,
    prep: "4 min", servings: "1", benefitTag: "Light",
    benefit: "Bright, sunny, and effortless.",
    ingredients: ["1 cup frozen mango", "1/2 cup frozen papaya (or extra mango)", "Juice of 1/2 lime", "3/4 cup coconut water", "1 tsp chia seeds", "1 scoop Radiant Reds (Glow Boost)"],
    method: ["Add coconut water, mango, and papaya to the blender.", "Add lime and chia.", "Blend until smooth and golden-orange.", "Finish with your Glow Boost and a quick pulse.", "Texture — smooth and tropical; naturally sweet, no added sugar needed.", "Swap — pineapple can replace papaya. Add a handful of spinach for greens; the color stays bright."],
    redsBoost: { why: "A scoop of Radiant Reds brings red-fruit polyphenols to a bright tropical base.", proof: ["Polyphenol-rich red fruits and roots", "Everyday antioxidant support"] } },
];

export type Ingredient = {
  name: string; tagline: string; description: string; gut: string; skin: string;
  alsoIn: string[];
};

export const INGREDIENTS: Ingredient[] = [
  { name: "Pomegranate", tagline: "Ellagic acid + punicalagins",
    description: "Two of the most studied polyphenols for skin health. Supports collagen protection and reduces UV-related skin damage.",
    gut: "Feeds beneficial bacteria; metabolized into urolithin A.", skin: "Clarity, elasticity, tone.",
    alsoIn: ["The Pomegranate Glow Elixir", "Radiant Reds blend"] },
  { name: "Raspberry", tagline: "Ellagitannins, vitamin C",
    description: "Tiny berries with one of the highest polyphenol densities by weight. Supports collagen production via vitamin C.",
    gut: "Soluble fiber feeds the microbiome.", skin: "Brightness, evenness.",
    alsoIn: ["Berry Bloom", "Beet Glow"] },
  { name: "Strawberry", tagline: "Vitamin C, ellagic acid",
    description: "More vitamin C than oranges by weight. Supports the collagen synthesis pathway your skin uses every day.",
    gut: "Polyphenols modulate inflammation in the gut lining.", skin: "Tone, firmness.",
    alsoIn: ["Berry Bloom"] },
  { name: "Tart cherry", tagline: "Anthocyanins, melatonin",
    description: "One of the highest-anthocyanin foods. Studied for skin elasticity, recovery, and sleep — all of which show in your face.",
    gut: "Anti-inflammatory effects in the gut lining.", skin: "Recovery, elasticity.",
    alsoIn: ["Cherry Cacao"] },
  { name: "Blueberry", tagline: "Anthocyanins, vitamin K",
    description: "Classic for a reason. The anthocyanins protect skin cells from oxidative damage every day.",
    gut: "Increases bifidobacteria diversity.", skin: "Protection, glow.",
    alsoIn: ["Berry Bloom"] },
  { name: "Plum", tagline: "Chlorogenic acid, fiber",
    description: "Underrated polyphenol source. The chlorogenic acid is the same beneficial compound found in green coffee.",
    gut: "Gentle motility support.", skin: "Tone evenness.",
    alsoIn: ["Plum & Rose"] },
  { name: "Watermelon", tagline: "Lycopene, citrulline",
    description: "Hydration plus lycopene — a carotenoid with skin-protective effects against UV stress.",
    gut: "Hydrates the gut lining.", skin: "UV defense, clarity.",
    alsoIn: ["Watermelon Reds"] },
  { name: "Black fig", tagline: "Soluble fiber, polyphenols",
    description: "One of the best prebiotic fruits. The fiber feeds the bacteria you spent the morning building up.",
    gut: "Prebiotic — feeds gut bacteria directly.", skin: "Indirect: better gut means clearer skin.",
    alsoIn: ["Fig & Almond"] },
  { name: "Beet", tagline: "Nitrates, betalains",
    description: "Nitrates support nitric oxide production and skin oxygenation. Betalains are powerful antioxidants.",
    gut: "Supports liver detox pathways.", skin: "Oxygenation, glow.",
    alsoIn: ["Beet Glow"] },
  { name: "Hibiscus", tagline: "Anthocyanins, quercetin",
    description: "Vivid red tea high in vascular-supportive polyphenols. Long traditional use for circulation and skin tone.",
    gut: "Mild prebiotic.", skin: "Tone, blood-vessel support.",
    alsoIn: ["Watermelon Reds"] },
  { name: "Cacao", tagline: "Flavanols, magnesium",
    description: "Cacao flavanols are some of the most-studied for skin hydration and circulation.",
    gut: "Modulates microbiome composition.", skin: "Hydration, density.",
    alsoIn: ["Cherry Cacao"] },
  { name: "Almond", tagline: "Vitamin E, healthy fats",
    description: "Vitamin E is a primary lipid-soluble antioxidant your skin barrier needs.",
    gut: "Fiber feeds beneficial bacteria.", skin: "Barrier strength.",
    alsoIn: ["Cherry Cacao", "Fig & Almond"] },
  { name: "Oat milk", tagline: "Beta-glucans",
    description: "Beta-glucans support gut lining and skin barrier. Gentle base for morning rituals.",
    gut: "Soothing soluble fiber.", skin: "Barrier support.",
    alsoIn: ["The Pomegranate Glow Elixir", "Cherry Cacao", "Fig & Almond"] },
  { name: "Almond milk", tagline: "Light base",
    description: "Low-sugar, gentle base. Pairs well with high-polyphenol fruits without competing.",
    gut: "Easy on digestion.", skin: "Neutral.",
    alsoIn: ["Berry Bloom"] },
  { name: "Chia", tagline: "Omega-3, fiber",
    description: "Plant omega-3 ALA and soluble fiber. Both support skin barrier and gut motility.",
    gut: "Forms a soothing gel.", skin: "Barrier, hydration.",
    alsoIn: ["Berry Bloom"] },
  { name: "Cinnamon", tagline: "Polyphenols, blood-sugar support",
    description: "A small pinch helps blunt morning blood sugar — relevant for skin clarity.",
    gut: "Mild antimicrobial.", skin: "Reduces glycation stress.",
    alsoIn: ["Cherry Cacao", "Fig & Almond"] },
  { name: "Honey", tagline: "Trace polyphenols",
    description: "A small amount of raw honey adds gentle sweetness and trace antioxidants.",
    gut: "Some prebiotic effect.", skin: "Indirect.",
    alsoIn: ["Plum & Rose"] },
  { name: "Rose water", tagline: "Calming aromatic",
    description: "Mildly anti-inflammatory and aromatic. A traditional addition to feminine wellness rituals.",
    gut: "Calming.", skin: "Soothing, calming.",
    alsoIn: ["Plum & Rose"] },
  { name: "Coconut yogurt", tagline: "Probiotics, fats",
    description: "Probiotic base with healthy medium-chain fats. Pairs beautifully with stone fruits.",
    gut: "Live cultures.", skin: "Indirect via gut.",
    alsoIn: ["Plum & Rose"] },
  { name: "Lime", tagline: "Vitamin C, brightness",
    description: "Brightens flavor and adds vitamin C without the bulk of orange juice.",
    gut: "Mild digestive support.", skin: "Vitamin C cofactor.",
    alsoIn: ["The Pomegranate Glow Elixir", "Watermelon Reds"] },
  { name: "Orange", tagline: "Vitamin C, hesperidin",
    description: "Hesperidin is a citrus flavonoid with vascular and skin-tone benefits.",
    gut: "Soluble fiber.", skin: "Tone, micro-circulation.",
    alsoIn: ["Beet Glow"] },
  { name: "Banana", tagline: "Potassium, prebiotics",
    description: "Resistant starch in slightly green bananas feeds gut bacteria.",
    gut: "Prebiotic.", skin: "Indirect.",
    alsoIn: ["Berry Bloom"] },
  { name: "Ginger", tagline: "Gingerols",
    description: "Warming, anti-inflammatory, and motility-supportive. Long traditional use in morning rituals.",
    gut: "Motility, anti-nausea.", skin: "Anti-inflammatory.",
    alsoIn: ["Beet Glow"] },
  { name: "Lemon", tagline: "Vitamin C, citric acid",
    description: "Warm lemon water is the gentlest way to begin the morning ritual.",
    gut: "Mild digestive support.", skin: "Vitamin C cofactor.",
    alsoIn: ["Warm lemon water (Day 1)"] },
  { name: "Radiant Reds", tagline: "NOURÉ blend",
    description: "The polyphenol-dense base of every morning. Pomegranate, beet, hibiscus, açaí, and more in one scoop.",
    gut: "Multi-source polyphenol load.", skin: "Glow, clarity, tone.",
    alsoIn: ["The Pomegranate Glow Elixir", "Watermelon Reds"] },
  { name: "Açaí", tagline: "Anthocyanins, healthy fats",
    description: "Amazonian berry with one of the highest antioxidant scores measured.",
    gut: "Polyphenol fermentation.", skin: "Protection, glow.",
    alsoIn: ["Radiant Reds"] },
  { name: "Green tea", tagline: "EGCG",
    description: "EGCG is one of the most studied skin-protective polyphenols.",
    gut: "Microbiome diversity.", skin: "UV defense, clarity.",
    alsoIn: ["Optional afternoon ritual"] },
  { name: "Turmeric", tagline: "Curcumin",
    description: "Curcumin is a strong anti-inflammatory; pair with black pepper for absorption.",
    gut: "Anti-inflammatory.", skin: "Tone, calmness.",
    alsoIn: ["Optional add-in"] },
  { name: "Mint", tagline: "Aromatic herb",
    description: "Cooling, digestion-supportive herb. A small handful elevates any morning blend.",
    gut: "Soothing.", skin: "Indirect.",
    alsoIn: ["Optional garnish"] },
  { name: "Strawberry leaf tea", tagline: "Quiet ritual",
    description: "A traditional women's wellness brew, quietly polyphenol-rich.",
    gut: "Mild astringent.", skin: "Indirect.",
    alsoIn: ["Optional afternoon ritual"] },
];

export type Polyphenol = {
  id: string; name: string; color: string; topBenefit: string; points: string[]; howTo: string;
};

export const POLYPHENOLS: Polyphenol[] = [
  { id: "pomegranate", name: "Pomegranate", color: "#9B1B3A", topBenefit: "Skin clarity & elasticity",
    points: ["Highest in punicalagins of any common fruit.", "Metabolized to urolithin A by gut bacteria.", "Supports collagen protection.", "Studied for UV-related skin protection.", "Best drunk in the morning."],
    howTo: "One serving daily — fresh seeds, juice, or a scoop of Radiant Reds." },
  { id: "acai", name: "Açaí", color: "#3E1A47", topBenefit: "Antioxidant density",
    points: ["One of the highest ORAC scores of any fruit.", "Rich in anthocyanins.", "Healthy fats support absorption of fat-soluble nutrients.", "Pairs well with banana and almond milk.", "Found in Radiant Reds."],
    howTo: "Frozen pulp blended into a smoothie, or via Radiant Reds." },
  { id: "blueberry", name: "Blueberry", color: "#3F4A8C", topBenefit: "Daily skin protection",
    points: ["Anthocyanin-rich.", "Studied for cognitive and skin benefits.", "Feeds bifidobacteria diversity.", "Easy daily addition.", "Wild varieties are denser."],
    howTo: "½ cup fresh or frozen, daily." },
  { id: "hibiscus", name: "Hibiscus", color: "#A02447", topBenefit: "Vascular & tone",
    points: ["Vivid red tea, anthocyanin-rich.", "Traditional use for circulation.", "Mild blood-pressure support.", "Cooling iced or warming hot.", "Pairs with lime and watermelon."],
    howTo: "1–2 cups daily, hot or cold." },
  { id: "beet", name: "Beet", color: "#6B1730", topBenefit: "Circulation & oxygenation",
    points: ["Nitrate-rich, supports nitric oxide.", "Betalains are unique antioxidants.", "Skin oxygenation benefit.", "Roast or steam to soften flavor.", "Pairs with raspberry and orange."],
    howTo: "1 small beet daily during the reset." },
  { id: "green-tea", name: "Green tea", color: "#3E5C3A", topBenefit: "EGCG defense",
    points: ["EGCG is one of the most studied polyphenols.", "Skin-protective in human studies.", "Supports microbiome diversity.", "Best brewed at lower temps to preserve EGCG.", "Skip late afternoon for sleep."],
    howTo: "1–2 cups in the morning or early afternoon." },
  { id: "turmeric", name: "Turmeric", color: "#C8893A", topBenefit: "Inflammation calm",
    points: ["Curcumin is anti-inflammatory.", "Pair with black pepper for absorption.", "Best with a fat source.", "Traditional women's wellness use.", "Adds warmth to morning blends."],
    howTo: "½ tsp daily with food and pepper." },
  { id: "cacao", name: "Cacao", color: "#4A2716", topBenefit: "Hydration & density",
    points: ["Cacao flavanols studied for skin hydration.", "Supports density of skin over time.", "Magnesium-rich.", "Use raw or minimally processed.", "Pairs with cherry and almond."],
    howTo: "1–2 tbsp raw cacao, several times a week." },
];

export const ARTICLES = [
  { id: "polyphenols", title: "What Polyphenols Actually Do for Your Skin",
    body: `Polyphenols are plant compounds — thousands of them — that act as the plant's defense against stress. When you eat them, they become part of your defense too.\n\nThe ones that matter most for skin are anthocyanins (the deep reds and purples), ellagitannins (pomegranate, raspberry), flavanols (cacao, green tea), and carotenoids (orange and red plants).\n\nThey work in two ways. First, directly: many polyphenols are absorbed and circulate in your skin, where they protect against oxidative stress every minute of the day. Second, indirectly: polyphenols feed the bacteria in your gut. Those bacteria metabolize the polyphenols into smaller, more powerful compounds — like urolithin A — that the body actually uses.\n\nThis is why one polyphenol-rich morning isn't enough. The compounds work in compounding fashion, building both their own circulating concentration and the gut bacteria that produce their active forms. Twenty-one days is the window where both layers reach a noticeable threshold.` },
  { id: "gut-skin", title: "The Gut-Skin Axis Explained Simply",
    body: `The gut-skin axis is the two-way communication line between your digestive system and your skin. It's not a metaphor. It's a measurable, studied relationship.\n\nHere is the simple version: your gut lining is one cell thick. When that lining is inflamed, immune signals leak into circulation. Those signals travel — and skin is one of their loudest expressions. Dullness, breakouts, sensitivity, redness: many of these begin in the gut.\n\nThe inverse is also true. When the gut lining is healthy and the microbiome is diverse, your skin gets a steady supply of anti-inflammatory signals and the metabolites of the polyphenols you eat. That's the glow.\n\nThe Inner Glow Reset is built around this axis. Every morning ritual feeds it. Every recipe is designed for it. The work happens inside, and the result happens at the surface.` },
  { id: "morning-timing", title: "Why Your Morning Timing Matters",
    body: `Polyphenols absorb best on a relatively empty stomach with hydration. That's why this ritual lives in the morning, not in the afternoon.\n\nYour body has just finished its longest fast of the day. Your gut lining is calm, your absorption is high, and your circadian rhythm is most receptive to the compounds you take in.\n\nA polyphenol-dense morning sets the tone for the rest of your day's inflammation profile. It's a small lever with a big effect.` },
  { id: "reading-skin", title: "How to Read Your Skin's Changes During a Reset",
    body: `Your skin renews on roughly a 27-day cycle, but the brightness of the surface changes faster. Here's what to watch for, and when:\n\nDays 1–7: Mostly internal. Energy may shift. Bloating may soften. Skin won't show you yet.\n\nDays 8–14: First visible signs. Often a softening of dullness. Sometimes an initial breakout as the gut shifts — this is normal and clears.\n\nDays 15–21: Visible glow. Tone evens. Under-eye lifts. Other people notice before you do.\n\nDay 22 onward: This is when 21 days of work becomes the new baseline. The ritual is now your morning, not your reset.` },
  { id: "reds-ingredients", title: "The Radiant Reds Ingredients — And What Each One Does",
    body: `Radiant Reds is built around one principle: polyphenol density. Each ingredient was chosen for what it contributes to the gut-skin axis.\n\nPomegranate brings ellagic acid and punicalagins — two of the most studied compounds for collagen protection.\n\nBeet brings nitrates and betalains — for circulation, oxygenation, and a unique class of antioxidants.\n\nHibiscus brings anthocyanins and vascular support — for tone and small-vessel health.\n\nAçaí brings one of the highest antioxidant scores measured in any fruit.\n\nRaspberry and strawberry bring ellagitannins and vitamin C — for the collagen synthesis pathway.\n\nThe scoop is what 21 days of feeding your gut-skin axis looks like — concentrated, every morning.` },
  { id: "after-21", title: "After 21 Days: How to Keep the Ritual",
    body: `Twenty-one days is enough to build a habit. It's not enough to finish a transformation.\n\nThe most common mistake is to treat day 22 as the end. Don't. The ritual that worked for 21 days is the ritual that works for 121.\n\nKeep the morning glass. Keep the slow start. Rotate the recipes. Add a second polyphenol moment in the afternoon if you want to deepen.\n\nThe Inner Glow Reset isn't a 21-day product. It's the entry point to a morning you keep.` },
];

export type BlendTip = { thick: string; thin: string; pro: string };

export const BLEND_TIPS: Record<string, BlendTip> = {
  "pomegranate-elixir": {
    thick: "Add ½ frozen banana or 2 tbsp coconut yogurt. The fat deepens the texture and makes it feel more like a meal.",
    thin: "Use ¾ cup oat milk instead of ½, or add a splash of cold hibiscus tea. Strain through a fine mesh for extra silk.",
    pro: "Chill the glass first. Pour slowly. The color is the ritual — let it land.",
  },
  "berry-bloom": {
    thick: "Add 1 tbsp almond butter or use half a frozen banana. Let it sit 5 minutes after blending — the chia blooms and thickens naturally.",
    thin: "Use 1¼ cups almond milk and skip the chia. Strain over ice for a bright, clean pour.",
    pro: "Freeze the berries the night before. Cold blending keeps the anthocyanins from degrading in heat.",
  },
  "cherry-cacao": {
    thick: "Double the almond butter to 2 tbsp and use ¾ cup oat milk. This becomes a proper morning meal.",
    thin: "Add an extra ¼ cup oat milk and skip the almond butter. Run the blender an extra 30 seconds for a silky finish.",
    pro: "Use frozen tart cherries straight from the bag — no need to thaw. The cold intensifies the dark flavor.",
  },
  "plum-rose": {
    thick: "Add 3 tbsp coconut yogurt and reduce rose water to ½ tsp. The yogurt rounds the tartness and gives it body.",
    thin: "Add 2 tbsp cold water and blend until completely smooth. This one is better thinner — let the rose water breathe.",
    pro: "Use very ripe plums — the skin is where most of the polyphenols live. Don't peel them.",
  },
  "watermelon-reds": {
    thick: "Freeze the watermelon cubes overnight. Blend frozen — it becomes a sorbet-style slush with no extra ingredients.",
    thin: "Double the hibiscus tea and serve over crushed ice. The palest, most refreshing version.",
    pro: "Brew the hibiscus tea strong, then chill overnight. Add Radiant Reds after blending, not before — heat degrades some polyphenols.",
  },
  "fig-almond": {
    thick: "Add 1 tbsp almond butter and use ¾ cup oat milk. The fig and almond together become almost caramel-like.",
    thin: "Use 1¼ cups oat milk and blend longer. Strain if the fig seeds bother you.",
    pro: "Soak dried figs in warm water for 15 minutes before blending — they open up completely and the texture becomes silky.",
  },
  "beet-glow": {
    thick: "Add 1 small frozen banana to balance the earthiness. The natural starch makes it thick and almost dessert-like.",
    thin: "Extra orange juice and no banana. Strain through a fine mesh — the result is a clear, jewel-red glass.",
    pro: "Roast the beet ahead of time and freeze in cubes. Game-changer for texture and sweetness.",
  },
  "golden-turmeric": {
    thick: "Use oat milk and whisk in ½ tsp coconut oil. The fat emulsifies everything and adds body.",
    thin: "Use almond milk and let it stay warm. Don't blend — just whisk gently.",
    pro: "Add a crack of black pepper — it increases curcumin absorption by up to 2000%. A pinch is enough.",
  },
  "matcha-cloud": {
    thick: "Add ½ frozen banana and use ¾ cup almond milk. Blend until completely smooth — it becomes thick and pale green.",
    thin: "Whisk the matcha separately, then pour over ice and top with almond milk. No blending needed.",
    pro: "Sift the matcha before whisking. Clumps are the enemy. A bamboo whisk in a zig-zag motion, not circular.",
  },
  "lavender-honey": {
    thick: "Stir in 1 tbsp raw honey and 2 tbsp coconut yogurt after steeping. Serve at room temperature.",
    thin: "Double the water, steep 3 minutes, strain well, serve over ice. The lightest, most delicate version.",
    pro: "Don't over-steep culinary lavender — 4 minutes maximum or it turns soapy.",
  },
  "rose-cardamom": {
    thick: "Add ¼ tsp coconut cream to the oat milk before warming. The result is luscious and almost dessert-like.",
    thin: "Reduce to ¾ cup oat milk and add ¼ cup water. Keep it warm, not hot.",
    pro: "Crush cardamom pods fresh if you have them — the fragrance is completely different from ground.",
  },
  "blueberry-basil": {
    thick: "Use frozen wild blueberries and add ½ banana. The frozen fruit makes it naturally thick without yogurt.",
    thin: "Add ¼ cup cold water and strain through a fine mesh. Serve very cold.",
    pro: "Add the basil last — just a few seconds in the blender. Over-blending turns it slightly bitter.",
  },
  "papaya-lime": {
    thick: "Add 2 tbsp coconut yogurt. The enzyme and fat combination is incredibly smooth.",
    thin: "Blend with ¼ cup cold water and strain. Papaya thins beautifully — it's almost juice-like.",
    pro: "Let papaya ripen until it's fully yielding. The more ripe, the more enzymes, the more digestive benefit.",
  },
  "peach-saffron": {
    thick: "Use ½ cup almond milk and add 1 tbsp almond butter. Luxurious texture.",
    thin: "Add ¼ cup extra almond milk. Serve over a single large ice cube.",
    pro: "Steep the saffron in warm milk — not hot water — for 10 minutes before blending. The milk extraction is richer.",
  },
  "fig-vanilla": {
    thick: "Use ¾ cup oat milk and blend in 2 tbsp almond butter. This is a full meal.",
    thin: "1¼ cups oat milk and strain. The natural sweetness of fig makes it work as a light drink.",
    pro: "Use a vanilla bean scraped directly if you can — the flavor depth is worth it.",
  },
  "cucumber-mint": {
    thick: "Don't — this one lives in thin territory. Freeze it in popsicle molds instead.",
    thin: "Add ¼ cup sparkling water at the end, don't blend the bubbles. Serve immediately.",
    pro: "Don't peel the cucumber — the skin has more silica and polyphenols than the flesh.",
  },
  "apricot-almond": {
    thick: "Add 1 tbsp almond butter and use ¾ cup oat milk. Let it rest 2 minutes — it thickens as it sits.",
    thin: "Use 1 cup oat milk and add a splash of cold water. Strain for a delicate, pale gold pour.",
    pro: "Use ripe apricots that yield to gentle pressure. The carotenoid content doubles at peak ripeness.",
  },
  "kiwi-spinach": {
    thick: "Add ½ frozen banana. The banana smooths the sharpness of kiwi and adds body.",
    thin: "Skip the banana, add ¼ cup more almond milk. Strain for a completely clear, jewel-green glass.",
    pro: "Kiwi skin is edible and has 3× the fiber of the flesh. Try blending whole if your blender is powerful.",
  },
  "vanilla-chia": {
    thick: "Add an extra tablespoon of chia and let it sit overnight rather than a few hours.",
    thin: "Use 1¼ cups oat milk in the mix. The ratio is everything with chia.",
    pro: "Stir twice during the first 10 minutes of refrigerating — this prevents clumping and gives the smoothest texture.",
  },
  "ginger-pear": {
    thick: "Add ½ banana and blend the ginger fully. Warming and filling.",
    thin: "Juice instead of blend — press pear and ginger through a juicer for a completely clear, spicy morning shot.",
    pro: "Freeze the pear first if you want it cold and thick. Fresh pear makes it thinner and more delicate.",
  },
  "honey-almond": {
    thick: "Use 2 tbsp almond butter instead of 1 and reduce oat milk to ¾ cup.",
    thin: "1¼ cups oat milk and just ½ tbsp almond butter. Warm and silky.",
    pro: "Warm gently — don't boil. Raw honey loses its enzymes above 40°C.",
  },
  "bonus-cacao-tonic": {
    thick: "Add 1 tbsp almond butter and reduce to ¾ cup oat milk. This becomes a true nightcap.",
    thin: "Use 1¼ cups oat milk and just whisk — no need to blend.",
    pro: "Drink this 90 minutes before bed. The magnesium in cacao supports sleep quality.",
  },
  "bonus-rose-collagen": {
    thick: "Add 2 tbsp coconut yogurt and stir gently — don't over-mix.",
    thin: "More sparkling water, less sparkling. The lighter it is, the more elegant.",
    pro: "Add the sparkling water last, after everything else is mixed.",
  },
  "bonus-green-glow": {
    thick: "Add ½ frozen banana. It turns completely smooth and green.",
    thin: "Skip the banana, strain, serve very cold.",
    pro: "Blend the mint for just 3 seconds — any longer and it can turn bitter.",
  },
  "bonus-warm-elixir": {
    thick: "Muddle the berries hard before adding the tea. Let it steep together for 2 extra minutes.",
    thin: "Strain and serve hot without muddling — a clean, garnet-colored cup.",
    pro: "Add Radiant Reds only after the tea cools below 40°C — heat degrades heat-sensitive polyphenols.",
  },
  "bonus-glow-sorbet": {
    thick: "Use less coconut yogurt and blend from frozen — it comes out like ice cream.",
    thin: "Add 2 tbsp oat milk and blend until completely smooth.",
    pro: "Pre-freeze your bowl. Cold bowl, cold sorbet, right consistency.",
  },
};

export type GlowBoostStory = { headline: string; skinStory: string; moment: string };

export const GLOW_BOOST_STORIES: Record<string, GlowBoostStory> = {
  "pomegranate-elixir": {
    headline: "Double the clarity in a single glass.",
    skinStory: "Pomegranate already delivers punicalagins — the compound your gut converts to urolithin A, which protects collagen. Add Radiant Reds and you're stacking a second pomegranate source with beet nitrates for circulation and hibiscus anthocyanins for tone. The result: the same polyphenol conversation happening at twice the volume, across more of your skin's systems simultaneously.",
    moment: "Add one scoop to the blender before blending. The color deepens. The flavor stays bright.",
  },
  "berry-bloom": {
    headline: "Your microbiome has been waiting for this combination.",
    skinStory: "Blueberries and strawberries feed bifidobacteria — a specific family of gut bacteria directly linked to clearer skin. Radiant Reds adds 24 additional polyphenol sources to that same feeding. The result isn't additive — it's multiplicative. Your microbiome diversifies faster, and diverse microbiomes produce the metabolites that show up as tone and brightness.",
    moment: "Stir in after blending, not before. The blueberry and Reds stay visually separate — swirl once before drinking.",
  },
  "cherry-cacao": {
    headline: "Anti-inflammatory stacking — for the skin that holds onto stress.",
    skinStory: "Tart cherry anthocyanins calm systemic inflammation. Cacao flavanols support skin density and hydration at the cellular level. Radiant Reds adds hibiscus, açaí, and beet — all with overlapping anti-inflammatory mechanisms. If stress shows on your face first, this combination works on every channel that stress uses. Less puffiness. Less redness. Faster morning recovery.",
    moment: "Blend Radiant Reds in with everything. The cherry-cacao flavor carries it completely.",
  },
  "plum-rose": {
    headline: "Gentle ritual, maximum polyphenol yield.",
    skinStory: "Plum delivers chlorogenic acid — the same polyphenol found in green coffee, studied for even skin tone. Rose water is calming to the nervous system, which calms cortisol, which shows up on your skin as less reactivity. Add Radiant Reds and the gentle ritual becomes a full polyphenol event without disturbing its softness. Your skin gets the calming properties and the active compounds.",
    moment: "Stir Radiant Reds into the finished bowl — it folds into the plum color beautifully.",
  },
  "watermelon-reds": {
    headline: "Hydration meets polyphenol density.",
    skinStory: "Watermelon is lycopene-rich — a carotenoid that accumulates in skin tissue and acts as internal UV protection. Hibiscus adds anthocyanins for vascular support and micro-circulation. Radiant Reds layers beet nitrates — improving blood flow to the skin — on top of all of that. The result is a glass that hydrates from the inside while feeding every layer of your skin's defense system.",
    moment: "Stir Radiant Reds in after blending — don't blend it. The watermelon flavor stays pure and the Reds blends smoothly.",
  },
  "fig-almond": {
    headline: "The prebiotic-polyphenol duo your gut notices first.",
    skinStory: "Fig fiber is prebiotic — it feeds gut bacteria directly. Polyphenols feed a different layer of the same system. Together, they're the combination your microbiome responds to fastest. Radiant Reds brings 27 polyphenol sources to sit alongside the fig's fiber, creating a gut environment where the bacteria that produce skin-clearing metabolites can genuinely thrive.",
    moment: "Add Radiant Reds to the blender with everything. The creamGold color takes on a richer, warmer tone.",
  },
  "beet-glow": {
    headline: "Circulation, doubled. Glow, accelerated.",
    skinStory: "Beet nitrates drive nitric oxide — which dilates blood vessels, improving circulation and skin oxygenation. That's what 'lit from within' means biologically. Radiant Reds adds more beet and layers hibiscus for vascular support. The result: your skin gets more oxygen, more nutrient delivery, and better color saturation. This is the recipe that makes other people ask what you're doing differently.",
    moment: "Add Radiant Reds in the blender — it deepens the jewel color and amplifies the earthy-sweet flavor.",
  },
  "golden-turmeric": {
    headline: "Two anti-inflammatory systems, one warm glass.",
    skinStory: "Curcumin and polyphenols work on overlapping but distinct anti-inflammatory pathways. Curcumin suppresses specific inflammatory signals; polyphenols calm a broader inflammatory environment and feed the bacteria that regulate it. Adding Radiant Reds after it cools means you're running both systems simultaneously — and the gut-skin axis benefits from both. This is the glass for the woman whose skin reacts to everything.",
    moment: "Wait until the latte cools to drinking temperature. Stir in Radiant Reds then — heat kills some polyphenols.",
  },
  "matcha-cloud": {
    headline: "EGCG and anthocyanins — two polyphenol families, two skin systems.",
    skinStory: "EGCG (the primary polyphenol in matcha) works primarily as a UV-protective and anti-oxidative compound in the skin. Anthocyanins (the primary polyphenols in Radiant Reds) work primarily via the gut-skin axis — feeding bacteria that produce the metabolites your skin uses for tone and clarity. These two families don't compete — they work through different mechanisms and cover more of your skin's needs than either could alone.",
    moment: "Stir Radiant Reds into the finished glass over ice. The matcha green and Reds garnet swirl — drink before it fully blends for the full effect.",
  },
  "lavender-honey": {
    headline: "Calm your nervous system and feed your skin — at the same time.",
    skinStory: "Lavender calms the nervous system. A calm nervous system produces less cortisol. Cortisol at high levels breaks down collagen, increases oil production, and shows up as dullness and reactivity. Radiant Reds adds the polyphenol layer that actively feeds the gut bacteria regulating inflammation. The combination works on skin from both the top-down (nervous system → skin) and the bottom-up (gut → skin) simultaneously.",
    moment: "Add Radiant Reds after the tea cools completely. Stir gently — this should stay delicate.",
  },
  "rose-cardamom": {
    headline: "Feminine, warming, and now fully polyphenol-backed.",
    skinStory: "Cardamom contains essential oils that are mildly anti-inflammatory and digestive-supportive. Rose water calms the nervous system. This glass is already doing quiet, real work. Add Radiant Reds and that quiet work gets amplified — the polyphenols feed the gut that's already been soothed, and the skin downstream gets both the calming signals and the active compounds for brightness and tone.",
    moment: "Wait until it reaches drinking temperature. Stir in Radiant Reds last. Sip slowly.",
  },
  "blueberry-basil": {
    headline: "Two anthocyanin sources hitting the same skin target from different angles.",
    skinStory: "Blueberries deliver anthocyanins that your gut converts into the metabolites that show up as skin brightness and protection. Radiant Reds delivers wild blueberry, açaí, and pomegranate — all hitting the same anthocyanin pathway, each with a slightly different molecular profile. Your gut converts all of them. More diversity means more of the metabolites that cross the gut-skin axis and reach your face.",
    moment: "Blend Radiant Reds in with the fruit. The deep blue-purple color intensifies — striking and saturated.",
  },
  "papaya-lime": {
    headline: "Enzymes open the door. Polyphenols walk through.",
    skinStory: "Papain — papaya's primary enzyme — supports digestion and reduces gut inflammation. A calmer gut is a more permeable membrane for the polyphenols that follow it. Radiant Reds, added alongside papaya, benefits from this enzymatic opening. The polyphenols absorb more efficiently in a gut that's been primed by papain. This is the sequence your microbiome notices.",
    moment: "Stir Radiant Reds into the finished glass — don't blend it in. The enzyme stays more active that way.",
  },
  "peach-saffron": {
    headline: "The mood-skin connection, fully supported.",
    skinStory: "Saffron has been studied for mood support — and mood affects skin. Chronic low-grade sadness or anxiety elevates cortisol, which degrades collagen and dulls tone. Radiant Reds layers polyphenols that specifically feed gut bacteria involved in neurotransmitter production — including the same pathways saffron touches. This glass works on your skin through your nervous system, your gut, and your circulation.",
    moment: "Add Radiant Reds after blending, before topping with cinnamon. Stir once.",
  },
  "fig-vanilla": {
    headline: "Prebiotic fiber meets polyphenol density — the gut's favorite combination.",
    skinStory: "Fig's soluble fiber is the substrate — it feeds the bacteria. Radiant Reds delivers the polyphenols those bacteria ferment into the compounds that reach your skin. It's the same relationship as soil and seeds: the fiber creates the environment, the polyphenols grow what your skin needs. Fig and Reds together accelerate the microbiome shift that shows up first as clearer digestion, then as clearer skin.",
    moment: "Add Radiant Reds to the blender. The vanilla and Reds create a complex, warm aroma that makes the morning feel like something.",
  },
  "cucumber-mint": {
    headline: "Hydration unlocks polyphenol absorption.",
    skinStory: "Polyphenols absorb most efficiently when you're well-hydrated. Cucumber is over 95% water — it actively prepares the gut environment for what comes next. Radiant Reds, added to this glass, arrives in the most receptive gut state possible. The polyphenols move faster, absorb more completely, and reach the gut bacteria that run your skin's glow engine.",
    moment: "Stir Radiant Reds into the finished cooler after straining. The clear cucumber base takes on a deep garnet color — serve immediately.",
  },
  "apricot-almond": {
    headline: "Two pigment families, one lit-from-within effect.",
    skinStory: "Apricots are beta-carotene-rich — a carotenoid that the body converts to vitamin A and accumulates in skin tissue, giving a warm, golden tone. Radiant Reds adds anthocyanins — the red and purple pigments that support tone evenness and circulation. Together, the warm gold of carotenoids and the deep red of anthocyanins are what researchers mean when they describe 'glow.' This is the glass for that.",
    moment: "Add Radiant Reds before blending. The apricot gold and Reds deepen into a stunning warm tone.",
  },
  "kiwi-spinach": {
    headline: "Vitamin C and polyphenols — the collagen connection.",
    skinStory: "Vitamin C is the rate-limiting factor in collagen synthesis — your body cannot make collagen without it. Kiwi delivers more vitamin C than oranges by weight. Radiant Reds adds anthocyanins that protect the collagen once it's made. The result is a glass that supports collagen at every stage: synthesis (vitamin C), protection from oxidation (polyphenols), and the gut environment where both are regulated.",
    moment: "Add Radiant Reds before blending. The green and garnet make a deep teal blend — unexpected, beautiful.",
  },
  "vanilla-chia": {
    headline: "Omega-3 and polyphenols for the skin barrier.",
    skinStory: "Skin barrier function is about fats and inflammation. Chia's ALA omega-3 feeds the lipid layer your barrier needs. Radiant Reds adds polyphenols that calm the inflammation that breaks that barrier down. The gut-skin axis is also at work: omega-3 and polyphenols together shift the microbiome toward bacteria that produce short-chain fatty acids — the compounds that repair the gut lining and, downstream, the skin.",
    moment: "Sprinkle Radiant Reds on top like a dusting. The crimson on cream is one of the most beautiful presentations in the reset.",
  },
  "ginger-pear": {
    headline: "Motility, microbiome, skin — in that order.",
    skinStory: "Ginger supports gut motility — the gentle movement that keeps digestion flowing. A moving gut is a healthier gut lining. Pear adds soluble fiber. Radiant Reds adds the polyphenols that feed the bacteria in the now-moving, fiber-supported gut. The chain runs: motility → healthy lining → better microbiome → cleaner skin. This glass supports every link.",
    moment: "Add Radiant Reds before blending. The ginger warmth and Reds complement each other completely.",
  },
  "honey-almond": {
    headline: "Clean energy that doesn't steal from your skin.",
    skinStory: "Blood sugar spikes glycate collagen — the process that makes skin look dull and aged. Almond fat and fiber blunt the morning blood sugar response. Radiant Reds adds polyphenols that, separately, slow glucose absorption and feed the bacteria that regulate insulin sensitivity. This glass keeps energy steady, keeps cortisol low, and keeps collagen intact — three skin wins from one morning ritual.",
    moment: "Stir Radiant Reds in after blending. Add a cinnamon dusting last — this is one of the most grounding morning cups in the reset.",
  },
  "bonus-cacao-tonic": {
    headline: "Evening polyphenols — while your skin does its overnight work.",
    skinStory: "Skin repair peaks between 11pm and 2am. The polyphenols you take in the evening are available in circulation during that repair window. Radiant Reds adds the polyphenol density cacao doesn't deliver — a quiet evening dose that reaches your skin's nighttime repair process and gives it more to work with while you sleep.",
    moment: "Wait until fully cooled. Stir in Radiant Reds. Sip slowly one hour before bed.",
  },
  "bonus-rose-collagen": {
    headline: "Vitamin C primes collagen. Polyphenols protect it.",
    skinStory: "Your body needs vitamin C to make collagen, and polyphenols to stop it from breaking down. Strawberry brings vitamin C. Radiant Reds brings the polyphenol protection layer. Together, they support both ends of the collagen lifecycle in a single glass. This is one of the most complete skin-support combinations in the entire recipe library.",
    moment: "Stir Radiant Reds into the finished glass before topping with sparkling water. The garnet color through the bubbles is striking.",
  },
  "bonus-green-glow": {
    headline: "Green pigments and red pigments — the full spectrum.",
    skinStory: "Chlorophyll (from cucumber and kiwi) is a green pigment that supports liver function and, through that, clearer skin. Anthocyanins (from Radiant Reds) are red and purple pigments that support the gut-skin axis directly. Plants use different pigment families to run different biological functions. Adding Radiant Reds to a chlorophyll-forward glass means you're running the full spectrum of plant-pigment skin support simultaneously.",
    moment: "Stir Radiant Reds into the strained glass, not the blender. The crimson drops through the green — beautiful.",
  },
  "bonus-warm-elixir": {
    headline: "Heat-sensitive ritual, carefully built.",
    skinStory: "Some polyphenols in Radiant Reds are heat-sensitive — they degrade above 40°C. This warm glass needs to cool before Radiant Reds goes in. Once it does, the hibiscus anthocyanins in the tea and the pomegranate, beet, and açaí in Radiant Reds create one of the deepest polyphenol concentrations in the entire recipe library. A warming cup that delivers a cold-process polyphenol punch.",
    moment: "Cool to drinking temperature — test with your wrist. Then stir in Radiant Reds and drink immediately.",
  },
  "bonus-glow-sorbet": {
    headline: "Dessert that works like a ritual.",
    skinStory: "Frozen berries retain their anthocyanins better than fresh during blending — cold processing preserves polyphenols that heat would degrade. Coconut yogurt adds live cultures alongside the fruit. Radiant Reds on top means the polyphenols hit an already-primed gut, where the probiotics and fruit fiber have prepared the environment. This is the most indulgent delivery mechanism in the reset.",
    moment: "Dust Radiant Reds on top like finishing powder. The crimson on ivory sorbet is the most beautiful thing you'll make in 21 days.",
  },
};

export const SOUNDS = [
  { id: "rain", name: "Morning Rain", duration: "8 min", url: "https://cdn.pixabay.com/audio/2022/03/10/audio_a8e603753c.mp3" },
  { id: "bowl", name: "Tibetan Bowl", duration: "5 min", url: "https://cdn.pixabay.com/audio/2022/10/18/audio_3433d6cea0.mp3" },
  { id: "forest", name: "Forest Light", duration: "10 min", url: "https://cdn.pixabay.com/audio/2022/03/09/audio_c8c8a73467.mp3" },
  { id: "birds", name: "Birdsong", duration: "7 min", url: "https://cdn.pixabay.com/audio/2021/10/07/audio_3f15f7e3a4.mp3" },
  { id: "silence", name: "Soft Silence", duration: "12 min", url: "https://cdn.pixabay.com/audio/2022/02/22/audio_d0c6ff1bdd.mp3" },
];

export const JOURNAL_PROMPTS: Record<number, (name: string) => string> = {
  1: (n) => `What made you start this reset today, ${n}?`,
  2: (n) => `What does your morning look like when it goes well, ${n}?`,
  3: () => `What did you notice in your body this morning?`,
  4: () => `Where in your body do you feel most alive right now?`,
  5: () => `What's one thing you're already doing right?`,
  6: () => `What does your skin feel like when you wake up?`,
  7: (n) => `One full week, ${n}. What's already shifting?`,
  8: () => `What does softness look like for you today?`,
  9: () => `Name a small ritual that's becoming yours.`,
  10: () => `What did you eat this week that made you feel lit up?`,
  11: () => `Look at your skin in natural light. What do you notice?`,
  12: () => `Where are you being too hard on yourself?`,
  13: () => `Write one sentence to your skin.`,
  14: (n) => `You're halfway, ${n}. What's shifted?`,
  15: () => `What have you stopped craving?`,
  16: () => `Name a moment of beauty from this week.`,
  17: () => `What feels lighter than it did on day one?`,
  18: () => `Where do you want to keep going past day 21?`,
  19: () => `What would make tomorrow feel sacred?`,
  20: () => `What are you carrying out of these 21 days?`,
  21: (n) => `This is the last entry, ${n}. What do you want to remember?`,
};

const SETS = {
  A: [
    "Tired is information, not failure. Your body is asking you to slow the morning, not push it.",
    "Rest is part of the ritual. The polyphenols still work while you sleep.",
    "Today, do less. The ritual is the glass — everything else can wait.",
    "Exhaustion isn't a setback. It's a signal that this work is reaching the parts that matter.",
  ],
  B: [
    "Your skin notices before your mirror does. Keep showing up.",
    "What you're describing is the gut-skin axis doing its job. The clarity you're feeling is the system working.",
    "This is the week it becomes visible. Stay in it.",
    "That glow you're seeing isn't from one morning. It's from all of them.",
    "Your skin is a record of the last twenty-one mornings. Keep writing it.",
  ],
  C: [
    "One missed day doesn't break a 21-day ritual. It just means today matters more. You're still in it.",
    "Hard is not the same as wrong. You came back. That's the ritual.",
    "Forgetting isn't failure. The ritual is what you return to, not what you never miss.",
    "Compassion first. Then the glass.",
  ],
  D: [
    "Hold onto this feeling. Write down the date. You'll want to remember this morning.",
    "This is what compounding looks like. You earned it.",
    "Days like this are why we built this ritual. Keep going.",
    "What you're feeling is what we hoped you'd feel. The work is paying interest now.",
  ],
  E: [
    "Bloating softens as the microbiome shifts. The fiber and polyphenols are doing slow, real work.",
    "The gut-skin axis you're feeling is the most important system in this reset. Trust the discomfort — it's reorganizing.",
    "Digestion changes are the first sign the ritual is reaching the right place.",
    "Your gut is the first organ to notice. Your skin is the second.",
  ],
  F: [
    "Noted. Your reset is taking shape.",
    "Even one sentence is a ritual. See you tomorrow.",
    "The ritual is the showing up. You did that today.",
    "Glow isn't linear. Your morning today is part of the line.",
    "Twenty-one days is built one journal entry at a time.",
  ],
};

export function reflectJournal(text: string, name: string): string {
  const t = text.toLowerCase();
  let pool = SETS.F;
  if (/\b(tired|exhausted|drained|wiped)\b/.test(t)) pool = SETS.A;
  else if (/\b(skin|clear|glow|bright|radiant)\b/.test(t)) pool = SETS.B;
  else if (/\b(hard|forgot|missed|skip|fail)\b/.test(t)) pool = SETS.C;
  else if (/\b(amazing|love|feel good|incredible|wonderful)\b/.test(t)) pool = SETS.D;
  else if (/\b(bloated|gut|digestion|stomach|belly)\b/.test(t)) pool = SETS.E;
  const pick = pool[Math.floor(Math.random() * pool.length)];
  return pick.replace(/\{name\}/g, name);
}

export type GroceryItem = { id: string; name: string; note?: string };
export type GroceryCategory = { name: string; items: GroceryItem[] };

export const GROCERY_LIST: GroceryCategory[] = [
  {
    name: "Fresh Produce",
    items: [
      { id: "pomegranate", name: "Pomegranate seeds or juice", note: "1 cup per use — frozen works" },
      { id: "raspberries", name: "Raspberries", note: "Fresh or frozen" },
      { id: "blueberries", name: "Blueberries", note: "Wild if available" },
      { id: "strawberries", name: "Strawberries" },
      { id: "banana", name: "Banana", note: "Slightly green = more prebiotic fiber" },
      { id: "plum", name: "Plum (2–3)", note: "Ripe, any variety" },
      { id: "watermelon", name: "Watermelon" },
      { id: "black-fig", name: "Black figs (4–6)", note: "Fresh or dried" },
      { id: "beet", name: "Beet (2 small)", note: "Pre-roast for the week" },
      { id: "tart-cherry", name: "Tart cherries", note: "Frozen or jarred unsweetened" },
      { id: "peach", name: "Peach or nectarine" },
      { id: "kiwi", name: "Kiwi (2)" },
      { id: "orange", name: "Orange" },
      { id: "lime", name: "Lime (4–5)" },
      { id: "lemon", name: "Lemon (2)" },
      { id: "cucumber", name: "Cucumber" },
      { id: "ginger", name: "Fresh ginger root" },
      { id: "mint", name: "Fresh mint" },
    ],
  },
  {
    name: "Bases",
    items: [
      { id: "oat-milk", name: "Oat milk (2 cartons)", note: "Unsweetened, barista or plain" },
      { id: "almond-milk", name: "Almond milk", note: "Unsweetened" },
      { id: "coconut-yogurt", name: "Coconut yogurt", note: "Plain, live cultures" },
      { id: "hibiscus-tea", name: "Hibiscus tea (dried or bags)" },
      { id: "green-tea", name: "Green tea (ceremonial-grade matcha or loose leaf)" },
    ],
  },
  {
    name: "Pantry",
    items: [
      { id: "reds", name: "Radiant Reds", note: "1 bag covers the full 21 days" },
      { id: "cacao", name: "Raw cacao powder" },
      { id: "almond-butter", name: "Almond butter", note: "No added sugar" },
      { id: "chia", name: "Chia seeds" },
      { id: "cinnamon", name: "Cinnamon (ground)" },
      { id: "honey", name: "Raw honey" },
      { id: "rose-water", name: "Rose water", note: "Culinary grade, small bottle" },
      { id: "vanilla", name: "Vanilla extract" },
      { id: "almonds", name: "Raw almonds (small bag)" },
      { id: "turmeric", name: "Turmeric (ground)" },
      { id: "black-pepper", name: "Black pepper", note: "Pairs with turmeric for absorption" },
    ],
  },
  {
    name: "Optional Upgrades",
    items: [
      { id: "collagen", name: "Collagen peptides (unflavored)", note: "Pairs with any recipe" },
      { id: "acai-packets", name: "Frozen açaí packets" },
      { id: "saffron", name: "Saffron (pinch jar)", note: "For the Peach & Saffron ritual" },
      { id: "cardamom", name: "Cardamom (ground)" },
    ],
  },
  {
    name: "Quick Glow Mornings",
    items: [
      { id: "qg-frozen-berries", name: "Frozen mixed berries", note: "Berry Reds Yogurt Shake" },
      { id: "qg-frozen-cherries", name: "Frozen cherries", note: "Cherry Cacao Calm Glow" },
      { id: "qg-frozen-mango", name: "Frozen mango", note: "Tropical Reds Quickie" },
      { id: "qg-frozen-papaya", name: "Frozen papaya", note: "Or extra mango" },
      { id: "qg-frozen-pineapple", name: "Frozen pineapple", note: "Cucumber Mint Lightness" },
      { id: "qg-cucumber", name: "Cucumber", note: "Cucumber Mint Lightness" },
      { id: "qg-greek-yogurt", name: "Greek yogurt or kefir", note: "Most quick recipes" },
      { id: "qg-coconut-water", name: "Coconut water", note: "Three quick recipes" },
      { id: "qg-cold-brew", name: "Cold brew or chilled coffee", note: "Mocha Reds Morning" },
      { id: "qg-flax", name: "Ground flax", note: "Or use chia seeds" },
      { id: "qg-vanilla", name: "Vanilla extract", note: "Pomegranate Vanilla Glow" },
      { id: "qg-protein", name: "Vanilla protein (optional)", note: "Mocha Reds Morning" },
    ],
  },
];

export const NOTIFICATIONS: Record<number, string> = {
  1: "Your reset begins this morning, {name}.",
  2: "Day 2. The ritual is still new. Show up anyway.",
  3: "Three mornings. Your gut is already paying attention.",
  4: "The first week is about showing up. You're doing it.",
  5: "Halfway through week one. Consistency is the active ingredient.",
  6: "Day 6. Your skin hasn't shown you everything yet. Stay in.",
  7: "One full week, {name}. Your body has been listening.",
  8: "Week two. This is where it deepens.",
  9: "Your polyphenol window is open. Use it this morning.",
  10: "Ten days in. The ritual is starting to feel like yours.",
  11: "Day 11. Dullness lifts in the second week. Watch for it.",
  12: "Your gut-skin axis is working. Keep feeding it.",
  13: "Tomorrow is the halfway point. You're almost there.",
  14: "Halfway, {name}. The ritual is becoming habit.",
  15: "Week three. This is where your skin shows the work.",
  16: "Day 16. What your mirror shows now is what you built.",
  17: "Four days left. Don't stop here.",
  18: "Day 18. The glow you're seeing is compounding.",
  19: "Two more mornings after this one.",
  20: "Day 20. Tomorrow is Day 21. You made it, {name}.",
  21: "This is Day 21. You showed up. Open the app.",
};

export const MILESTONES: Record<string, { title: string; sub: string; badge: string }> = {
  "day-1":  { title: "Day 1 is done, {name}.", sub: "The ritual has started.", badge: "The Beginning" },
  "day-7":  { title: "One week.",              sub: "Your gut has shifted. Your skin is listening.", badge: "Foundation Built" },
  "day-14": { title: "Halfway, {name}.",       sub: "The ritual is yours now.", badge: "Deep Glow" },
  "first-journal": { title: "You showed up for yourself today.", sub: "The first entry is the hardest.", badge: "First Words" },
  "streak-3": { title: "Three days in a row.", sub: "This is how rituals form.", badge: "Three Mornings" },
};
