/** Claim language that must never reach customers. Shared by the unit scan and the rendered-page e2e scan. */
// Disease, treatment, inflammation, UV, metabolic, detox, hormone and guaranteed-result language.
export const PROHIBITED = [
  /anti-?inflammat/i,
  /\binflamm/i,
  /\bUV\b/,
  /sun[- ]?protect/i,
  /blood[- ]?sugar/i,
  /\bglucose\b/i,
  /\binsulin\b/i,
  /glycat/i,
  /\bdetox(?!\?)/i,
  /\bliver\b/i,
  /oxygenat/i,
  /under-?eye/i,
  /melatonin/i,
  /cortisol/i,
  /\blymphatic\b(?!-)/i,
  /puffiness/i,
  /\bpores\b/i,
  /systemic/i,
  /suppress/i,
  /\bblunt/i,
  /\bcures?\b/i,
  /\btreat(s|ing)? (acne|skin|inflammation|disease|symptoms|conditions)/i,
  /\btreatment\b/i,
  /clinically/i,
  /\bproven\b/i,
  /guarantee/i,
  /blood-pressure/i,
  /anti-nausea/i,
  /antimicrobial/i,
  /\bmotility\b/i,
  /2000%/,
  /\bORAC\b/,
  /27 (additional )?polyphenol sources/i,
  /24 additional/i,
  /visible (results?|lift|shift|signs?|glow)/i,
  /collagen (protection|support|synthesis)/i,
  /protects? (the )?collagen/i,
  /skin[- ]protective/i,
  /skin barrier/i,
  /barrier strength/i,
  /repairs? itself/i,
  /transformation/i,
  /makes your skin better/i,
  /skin clarity/i,
];
// Unverified testimonial, typicality or customer-result language.
export const TESTIMONIAL = [
  /many (women )?notice/i,
  /women (say|notice|report)/i,
  /most women/i,
  /customers? (report|say|notice)/i,
  /users? experience/i,
  /other people (notice|ask)/i,
  /many quit/i,
  /I've kept up with it/,
];

// Promised physical results, especially tied to a particular day.
export const DAY_RESULT = [
  /dullness lifts/i,
  /(skin|mirror) shows/i,
  /skin hasn't shown/i,
  /glow you're seeing/i,
  /gut(-skin axis)? is (already|working)/i,
  /your body has been (listening|answering|responding)/i,
  /body has begun to respond/i,
  /microbiome (has noticed|is noticeably)/i,
  /becomes visible/i,
  /polyphenol window is open/i,
  /first visible/i,
];
